# Generated by Django 6.0.2 on 2026-02-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_descriptin',
            new_name='product_description',
        ),
    ]
